apiVersion: v1
data:
  values.yaml: |
    dl-priorityclasses:
      enabled: false
    altinity-clickhouse-operator:
      enabled: true
      serviceMonitor:
        enabled: false
      alerts:
        enabled: true
    ndh-core-namespace:
      enabled: true
    ndh-kuberay-operator:
      enabled: true
kind: ConfigMap
metadata:
  name: ${releaseName}-config-defaults
  namespace: ${releaseNamespace}
---