apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ${releaseName}-repo
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  provider: generic
  secretRef:
    name: ${releaseName}-artifactory-auth
  certSecretRef:
    name: ${releaseName}-artifactory-ca
  passCredentials: true
  insecure: true
  type: default
  url: https://artifactory.canaveral-corp.us-west-2.aws/artifactory/local-canaveral-helm-backup
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dl-base
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: dl-base
      interval: 10m
      sourceRef:
        kind: HelmRepository
        name: ${releaseName}-repo
        namespace: ${releaseNamespace}
      version: 0.0.1-opt.32773
  install:
    createNamespace: true
    crds: Skip
    remediation:
      retries: 30
  interval: 15s
  releaseName: dl-base
  targetNamespace: ${releaseNamespace}
  upgrade:
    crds: Skip
    remediation:
      retries: 30
  valuesFrom:
  - kind: ConfigMap
    name: ${releaseName}-config-defaults
---
