apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cm.yaml
- data-lens-certs.yaml
- data-lens-cm.yaml
- data-lens.yaml
- dl-common-cm.yaml
- dl-common.yaml
- helmrelease.yaml
- image-pull.yaml
- mspdeployedparams.yaml
- ndh-certs.yaml
- ndh-cm.yaml
- ndh.yaml
- pc-proxy.yaml
- priorityclasses.yaml
---
