apiVersion: v1
kind: ConfigMap
metadata:
  name: mspdeployedparams
  namespace: ndh-core
data:
  domain-name: cluster.local
  cluster-name: mirko-nkp
  cluster-uuid: eea9e75e-78fe-41c0-a008-d9c76d5c10b2
---
# pc-uuid must match the Service name in pc-proxy.yaml (pc-<pc-uuid>.ntnx-ikat).
apiVersion: v1
kind: ConfigMap
metadata:
  name: mspdeployedparams
  namespace: data-lens
data:
  domain-name: cluster.local
  cluster-name: mirko-nkp
  cluster-uuid: eea9e75e-78fe-41c0-a008-d9c76d5c10b2
  pc-uuid: fcab3de9-fabf-48b9-abe3-b298fd19c511
  prism-fqdn: 10.48.61.3
  prism-ip: 10.48.61.3
---
