apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-crds
  namespace: ${workspaceNamespace}
spec:
  interval: 6h
  retryInterval: 1m
  path: ./services/envoy-gateway/1.5.0/helmrelease
  prune: true
  force: true
  wait: true
  targetNamespace: envoy-gateway-system
  sourceRef:
    kind: GitRepository
    name: management
    name: kommander-flux
  timeout: 10m
  # Apply only the CRD manifest
  includes:
    - ./helmrelease/envoy-gateway-crds.yaml