apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nutanix-ai
  namespace: ${workspaceNamespace}
spec:
  interval: 1m
  url: "${ociRegistryURL:=oci://ghcr.io}/mesosphere/charts/nai-core"
  ref:
    tag: 2.4.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nutanix-ai
  namespace: ${workspaceNamespace}
spec:
  dependsOn:
    - name: kserve
      namespace: ${workspaceNamespace}
    - name: kserve-crd
      namespace: ${workspaceNamespace}
  chartRef:
    kind: OCIRepository
    name: nutanix-ai
    namespace: ${workspaceNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: nutanix-ai
  valuesFrom:
    - kind: ConfigMap
      name: nutanix-ai-2.4.0-nkp-defaults
    - kind: ConfigMap
      name: service-monitor-defaults
  targetNamespace: nai-system
