apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - job.yaml
  - nai-node-exporter-monitor.yaml
  - node-exporter-rbac-cluster-role.yaml
  # Certificate applier job
  - cert-apply-job.yaml