---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nutanix-ai-2.5.0-nkp-defaults
  namespace: ${workspaceNamespace}
data:
  values.yaml: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nutanix-ai-operators-2.5.0-nkp-defaults
  namespace: ${workspaceNamespace}
data:
  values.yaml: ""