apiVersion: v1
data:
  values.yaml: |
    # dl-priorityclasses is disabled because dl-base chart has them with different
    # values and, as they are immutable, HELM can not change them in place and an
    # error is thrown.
    dl-priorityclasses:
      enabled: false
    altinity-clickhouse-operator:
      enabled: true
      imagePullSecrets:
      - name: ${releaseName}-artifactory-pull
      serviceMonitor:
        enabled: false
      alerts:
        enabled: true
    ndh-core-namespace:
      enabled: true
    ndh-kuberay-operator:
      enabled: true
      imagePullSecrets:
      - name: ndh-iep-secret
kind: ConfigMap
# Gives the name '${releaseName}-config-defaults' to the ConfigMap and stores
# it in the namespace ${releaseNamespace}. It is later used to set the values
# that the chart is expecting.
metadata:
  name: ${releaseName}-config-defaults
  namespace: ${releaseNamespace}
---
