---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nutanix-ai-1.0.0-nkp-defaults
  namespace: ${workspaceNamespace}
data:
  values.yaml: |
    # Labels common to all components of nai-core
    labels:
      app.kubernetes.io/name: nai-iep

    # List of gateways to be used in the VirtualService.
    # These gateways determine the entry points for your traffic.
    virtualService:
      gateways:
      - knative-serving/knative-ingress-gateway

    # Image pull secret details
    imagePullSecret:
      # Name of the image pull secret
      name: nai-iep-secret
      # Image registry credentials
      credentials:
        registry: https://index.docker.io/v1/
        username: USERNAME
        password: PASSWORD
        email: EMAIL

    # Storage class name to be used by nai-db and prometheus db
    defaultStorageClassName: ""

    naiIepOperator:
      # IEP operator image details
      iepOperatorImage:
        image: docker.io/nutanix/nai-iep-operator
        tag: latest
      
      iepOperatorResources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 100Mi

      modelProcessorImage:
        image: docker.io/nutanix/nai-model-processor
        tag: latest

      modelProcessorResources:
        limits:
          cpu: ""
          memory: ""
        requests:
          cpu: ""
          memory: ""

      retainModelProcessorJob: "false"

    naiInferenceUi:
      naiUiImage:
        image: docker.io/nutanix/nai-inference-ui
        tag: latest
      
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi   

      naiApiUrl: "http://nai-api.nai-system.svc.cluster.local:7000"

    naiApi:
      naiApiImage:
        image: docker.io/nutanix/nai-api
        tag: latest

      naiApiResources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 8
          memory: 4Gi
      
      naiMigrateInitContainerResources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 1
          memory: 1Gi   
      
      naiMigrateJobResources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi

      superAdmin:
        username: admin
        password: Nutanix.123
        email: admin@nutanix.com
        firstName: admin

      storageClassName: nai-nfs-storage

      supportedKserveRuntimeImage: "quay.io/saileshd1402/huggingfaceserver:v0.14.0"
      supportedTGIImage: "artifactory-edge-01.corp.p10y.ntnxdpro.com/canaveral-legacy-docker/nutanix-core/nai-tgi:2.3.1"
      naiMonitoringUrl: "http://nai-prometheus.nai-system.svc.cluster.local:9090"

    naiDatabase:
      naiDbImage:
        image: docker.io/nutanix/nai-postgres:16.1-alpine

      service:
        port: 5432

      postgresql:
        postgresUser: nai-api-user
        postgresPassword: nai-api-password
        postgresDatabase: nai_iep
        postgresPort: "5432"
        postgresHost: nai-db

      resources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 4
          memory: 4Gi

      storageSpec:
        resources:
          requests:
            storage: 4Gi  

    naiMonitoring:
      prometheus:
        image:
          registry: quay.io
          repository: prometheus/prometheus
          tag: v2.54.0
        version: v2.54.0
        replicas: 1
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: 8
            memory: 4Gi
        storageSpec:
          resources:
            requests:
              storage: 20Gi
        persistentVolumeClaimRetentionPolicy:
          whenScaled: Retain
          whenDeleted: Delete

      kubeScheduler:
        service:
          enabled: false
        serviceMonitor:
          enabled: false

      nodeExporter:
        serviceMonitor:
          enabled: false

      dcgmExporter:
        podLevelMetrics: false
        serviceMonitor:
          enabled: false
