---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nutanix-ai-1.0.0-nkp-defaults
  namespace: ${workspaceNamespace}
data:
  values.yaml: |
    # Labels common to add components of nai-core
    labels:
      app.kubernetes.io/name: nai-iep

    # List of gateways to be used in the VirtualService.
    # These gateways determine the entry points for your traffic.
    virtualService:
      gateways:
        - knative-serving/knative-ingress-gateway

    # Image pull secret Details
    imagePullSecret:
      # Name of the image pull secret
      name: nai-iep-secret
      # Image registry credentials
      credentials:
        registry: https://index.docker.io/v1/
        username: USERNAME
        password: PASSWORD
        email: EMAIL

    # Storage class name to be used by nai-db and prometheus db
    defaultStorageClassName: ""

    naiIepOperator:
      # IEP operator image details
      iepOperatorImage:
        # IEP operator image name
        image: docker.io/nutanix/nai-iep-operator
        # IEP operator image tag
        tag: latest
      iepOperatorResources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 100Mi

      # Model processor image details
      modelProcessorImage:
        # Model Processor image name
        image: docker.io/nutanix/nai-model-processor
        # Model Processor image tag
        tag: latest

      # Configuration for resource limits and requests for the model processor.
      modelProcessorResources:
        limits:
          cpu: ""
          memory: ""
        requests:
          cpu: ""
          memory: ""
      
      # Determines whether the model processor job should be retained after completion.
      # Acceptable values:
      # - "true": Retain the job after completion.
      # - "false": Delete the job after completion.
      retainModelProcessorJob: "false"

    naiInferenceUi:
      # NAI UI image details
      naiUiImage:
        # The name of the NAI UI Docker image
        image: docker.io/nutanix/nai-inference-ui
        # The tag of the Docker image to be used
        tag: latest

      # Resources for nai-ui container
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi   

      # The URL for the NAI API service
      naiApiUrl: "http://nai-api.nai-system.svc.cluster.local:7000"

    naiApi:
      # NAI API image details
      naiApiImage:
        # The name of the NAI API Docker image
        image: docker.io/nutanix/nai-api
        # The tag of the Docker image to be used
        tag: latest

      # Resources for nai-api container
      naiApiResources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 8
          memory: 4Gi
      
      # Resources for nai-api-db-migrate job container
      naiMigrateInitContainerResources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 1
          memory: 1Gi   

      naiMigrateJobResources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi

      # Details of super admin (first user in the nai system)
      superAdmin:
        username: admin
        password: Nutanix.123
        email: admin@nutanix.com
        firstName: admin

      # Storage class name to be used nai-iep for storing models
      storageClassName: nai-nfs-storage

      # supportedKserveRuntimeVersion Image in model catalog
      supportedKserveRuntimeImage: "docker.io/nutanix/nai-kserve-huggingfaceserver:v0.14.0"

      # supportedTGIRuntimeImage
      supportedTGIImage: "docker.io/nutanix/nai-tgi"
      supportedTGIImageTag: "2.3.1-825f39d"
      
      # The URL for NAI prometheus service
      naiMonitoringUrl: "http://nai-prometheus.nai-system.svc.cluster.local:9090"

    naiDatabase:
      naiDbImage:
        # The name of the NAI DB Docker image
        image: docker.io/nutanix/nai-postgres:16.1-alpine

      # Postgres sql service port
      service:
        port: 5432

      # Postgres sql details
      postgresql:
        postgresUser: nai-api-user
        postgresPassword: nai-api-password
        postgresDatabase: nai_iep
        postgresPort: "5432"
        postgresHost: nai-db
      
      # Resources for nai-db container
      resources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 4
          memory: 4Gi
      
      # Storage spec for of nai-db
      storageSpec:
        resources:
          requests:
            storage: 4Gi  

    # Values for nai-monitoring stack deployment.
    # Values for node-exporter, kube-scheduler and dcgm-exporter service monitors are populated in env specific values files.
    naiMonitoring:
      ## Deploy prometheus
      prometheus:
        # Image for prometheus pod
        image:
          registry: quay.io
          repository: prometheus/prometheus
          tag: v2.54.0
        version: v2.54.0
        # Number of prometheus pods to deploy
        replicas: 1
        # Resources for prometheus pod
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: 8
            memory: 4Gi
        # Prometheus db storage spec
        storageSpec:
          resources:
            requests:
              storage: 20Gi
        # PVC retention policy during helm uninstall i.e. if statefulset is deleted.
        persistentVolumeClaimRetentionPolicy:
          whenScaled: Retain
          whenDeleted: Delete

      ## Component scraping kube scheduler
      kubeScheduler:
        service:
          enabled: false
        serviceMonitor:
          enabled: false

      ## Component scraping node exporter
      nodeExporter:
        serviceMonitor:
          enabled: false

      ## Component scraping dcgm exporter
      dcgmExporter:
        podLevelMetrics: false
        serviceMonitor:
          enabled: false
