---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-monitor-defaults
  namespace: ${workspaceNamespace}
data:
  values.yaml: |-
    naiMonitoring:
      dcgmExporter:
        podLevelMetrics: true
        serviceMonitor:
          enabled: true
          endpoint:
            targetPort: 9400
          namespaceSelector:
            matchNames:
            - ${workspaceNamespace}
          serviceSelector:
            matchLabels:
              app: nvidia-dcgm-exporter
