apiVersion: v1
kind: ConfigMap
metadata:
  name: nai-operators-pre-delete-hook-cm
  namespace: nai-system
data:
  WORKSPACE_NAMESPACE: "${workspaceNamespace}"
  HELMRELEASE_NAME: "nutanix-ai"
  POLL_INTERVAL: "10"
  TIMEOUT: "1800"