---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: ${workspaceNamespace}
spec:
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: v1.5.0
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: ${workspaceNamespace}
spec:
  interval: 15s
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: ${workspaceNamespace}
  install:
    crds: Skip
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    crds: Skip
    remediation:
      retries: 30
  releaseName: eg
  targetNamespace: envoy-gateway-system
  valuesFrom:
    - kind: ConfigMap
      name: envoy-gateway-1.5.0-nkp-defaults