apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nutanix-data-services
  namespace: ${workspaceNamespace}
spec:
  interval: 1m 
  url: "${ociRegistryURL:=oci://ghcr.io}/mesosphere/charts/ndk"
  ref:
    tag: 1.3.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nutanix-data-services
  namespace: ${workspaceNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: nutanix-data-services
    namespace: ${workspaceNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false # Since "ntnx-system" namespace is already created during csi installation.
  upgrade:
    remediation:
      retries: 30
  releaseName: nutanix-data-services
  valuesFrom:
    - kind: ConfigMap
      name: nutanix-data-services-1.3.0-defaults
  targetNamespace: ntnx-system