---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve-crd
  namespace: ${workspaceNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ghcr.io-kserve-crd-helm-releases
    namespace: ${workspaceNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: kserve-crd
  targetNamespace: kserve
