apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nai-otel-role
rules:
  - apiGroups: [""]
    resources: ["services/kube-prometheus-stack-prometheus-node-exporter"]
    verbs: ["get"]