---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-monitor-defaults
  namespace: ${workspaceNamespace}
data:
  values.yaml: |-
    naiMonitoring:
      dcgmExporter:
        serviceMonitor:
          namespaceSelector:
            matchNames:
            - ${workspaceNamespace}