---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio-release.storage.googleapis.com-helm-releases
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: supported
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 10m
