---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kserve-0.15.0-nkp-defaults
  namespace: ${workspaceNamespace}
data:
  values.yaml: |-
    kserve:
      controller:
        deploymentMode: RawDeployment
        gateway:
          disableIngressCreation: true
