---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-crds
  namespace: ${workspaceNamespace}
spec:
  interval: 6h
  retryInterval: 1m
  path: ./applications/envoy-gateway/1.5.0/crds
  prune: true
  force: true
  wait: true
  targetNamespace: envoy-gateway-system
  sourceRef:
    kind: GitRepository
    name: nai-gitrepository
    namespace: ${workspaceNamespace}
  timeout: 10m

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nai-gitrepository
  namespace: ${workspaceNamespace}
spec:
  interval: 1m0s
  url: https://github.com/nutanix-cloud-native/nkp-nutanix-product-catalog.git
  ref:
    branch: NAI-3088-v2
