---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ghcr.io-nai-core-crds
  namespace: ${workspaceNamespace}
spec:
  url: oci://repos.ntnxdpro.com/ai-nai-core/nai-core-crds
  ref:
    tag: 0.1.0_build.1942
  secretRef:
    name: artifactory-secret
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nai-core-crds
  namespace: ${workspaceNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ghcr.io-nai-core-crds
    namespace: ${workspaceNamespace}
  dependsOn:
    - name: kserve
      namespace: ${workspaceNamespace}
    - name: kserve-crd
      namespace: ${workspaceNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: nai-core-crds
  targetNamespace: nai-system
  values:
    naiAIGateway:
      enabled: false
