---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ghcr.io-nai-operators
  namespace: ${workspaceNamespace}
spec:
  url: oci://repos.ntnxdpro.com/ai-nai-core/nai-operators
  ref:
    tag: 0.1.0_build.2393
  secretRef:
    name: artifactory-secret
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nutanix-ai-operators
  namespace: ${workspaceNamespace}
spec:
  chartRef:
    kind: OCIRepository
    name: ghcr.io-nai-operators
    namespace: ${workspaceNamespace}
  dependsOn:
    - name: kserve
      namespace: ${workspaceNamespace}
    - name: kserve-crd
      namespace: ${workspaceNamespace}   
    - name: opentelemetry-operator
      namespace: ${workspaceNamespace}
  interval: 15s
  install:
    remediation:
      retries: 5
    createNamespace: true
    crds: Skip
  upgrade:
    remediation:
      retries: 5
    crds: Skip
  releaseName: nutanix-ai-operators
  targetNamespace: nai-system
  valuesFrom:
    - kind: ConfigMap
      name: nutanix-ai-operators-2.5.0-nkp-defaults
    - kind: ConfigMap
      name: nutanix-ai-config-overrides
      optional: true
    - kind: ConfigMap
      name: nutanix-ai-cluster-overrides
      optional: true
    - kind: ConfigMap
      name: nutanix-ai-overrides
      optional: true
