# Kubernetes versions
k8s_versions:
  - 1.35.0
  - 1.36.0

# use strict validation (reject unknown fields in resources)
strict: true

# load additional CRDs (URLs of CRD yaml files)
additional_crds:
 - https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/cert-manager.io_certificates.yaml
 - https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/cert-manager.io_issuers.yaml
