apiVersion: batch/v1
kind: Job
metadata:
  name: nai-postinstall
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: nai-postinstall
      restartPolicy: OnFailure
      containers:
        - name: post-install-nai-patch
          image: bitnami/kubectl:1.30.5
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for istio-ingressgateway external IP/FQDN..."

              for i in $(seq 1 5); do
                IP=$(kubectl get svc istio-ingressgateway -n istio-system -ojsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null)
                HOSTNAME=$(kubectl get svc istio-ingressgateway -n istio-system -ojsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null)
                if [ -n "$IP" ] || [ -n "$HOSTNAME" ]; then
                  break
                fi
                echo "Waiting..."; sleep 2
              done

              ENDPOINT="https://${IP:-$HOSTNAME}/"
              echo "Endpoint resolved: $ENDPOINT"

              kubectl patch configmap nai-ui -n {{ .Release.Namespace }} \
                -p "{\"data\":{\"dashboardLink\":\"${ENDPOINT}\"}}"

              echo "Dashboard link updated successfully."
