---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: ${workspaceNamespace}
spec:
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio-release.storage.googleapis.com-helm-releases
        namespace: ${workspaceNamespace}
      version: 1.20.8
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: istio-base
  targetNamespace: istio-system
