---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kserve-crd
  namespace: ${workspaceNamespace}
spec:
  chart:
    spec:
      chart: kserve-crd
      sourceRef:
        kind: HelmRepository
        name: ghcr.io-kserve-crd-helm-releases
        namespace: ${workspaceNamespace}
      version: v0.14.0-rc1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: kserve-crd
  targetNamespace: kserve
