---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kserve
  namespace: ${workspaceNamespace}
spec:
  chart:
    spec:
      chart: kserve
      sourceRef:
        kind: HelmRepository
        name: ghcr.io-kserve-helm-releases
        namespace: ${workspaceNamespace}
      version: 1.0.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: kserve
  targetNamespace: kserve
