apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nutanix-ai.yaml
  - kserve-crd.yaml
  - kserve.yaml
  - ../../../helm-repositories/ntnx-charts
  - ../../../helm-repositories/kserve-crd
  - ../../../helm-repositories/kserve
  - nai-self-signed-cert.yaml
  - nai-ui-dashboard-cm.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/servers
      value: |-
        - hosts:
          - '*'
          port:
            name: http
            number: 80
            protocol: HTTP
          # Upgrade HTTP to HTTPS
          tls:
            httpsRedirect: true
        - hosts:
          - '*'
          port:
            name: https
            number: 443
            protocol: HTTPS
          tls:
            mode: SIMPLE
            credentialName: nai-self-signed-cert
  target:
    group: networking.istio.io
    version: v1
    kind: Gateway
    name: knative-ingress-gateway
    namespace: knative-serving
