apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nutanix-ai.yaml
  - istio-base.yaml
  - istiod.yaml
  - istio-ingressgateway.yaml
  - kserve-crd.yaml
  - kserve.yaml
  - ../../../helm-repositories/ntnx-charts
  - ../../../helm-repositories/istio-charts
  - ../../../helm-repositories/kserve-crd
  - ../../../helm-repositories/kserve

