apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nai-self-signed-cert
  namespace: istio-system
spec:
  secretName: nai-self-signed-cert
  commonName: nai.example.com
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - nai.example.com
