---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nutanix-ai
  namespace: ${workspaceNamespace}
spec:
  dependsOn:
    - name: istio-base
      namespace: ${workspaceNamespace}
    - name: istio-ingressgateway
      namespace: ${workspaceNamespace}
    - name: istiod
      namespace: ${workspaceNamespace}
    - name: kserve
      namespace: ${workspaceNamespace}
    - name: kserve-crd
      namespace: ${workspaceNamespace}
  chart:
    spec:
      chart: nai-core
      sourceRef:
        kind: HelmRepository
        name: nutanix.github.io-helm-releases
        namespace: ${workspaceNamespace}
      version: 1.0.0-rc1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: nutanix-ai
  valuesFrom:
    - kind: ConfigMap
      name: nutanix-ai-1.0.0-nkp-defaults
  targetNamespace: nai-system
