name: Publish Chart to GHCR

on:
  workflow_dispatch:
    inputs:
      chart_repo:
        description: 'Source repository URL for the chart (e.g., https://mesosphere.github.io/charts/staging)'
        type: string
        required: true
      chart_name:
        description: 'Helm chart name (e.g., ndk, nutanix-ai, kserve, envoy-gateway etc.)'
        type: string
        required: true
      chart_version:
        description: 'Helm chart version'
        type: string
        required: true

jobs:
  push-chart:
    name: Publish ${{ github.event.inputs.chart_name }}@${{ github.event.inputs.chart_version }} to GHCR
    runs-on:
      - self-hosted-nutanix-medium
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install NIX
        uses: cachix/install-nix-action@v31

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: true
          skip-nix-installation: true

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish ${{ github.event.inputs.chart_name }}@${{ github.event.inputs.chart_version }} to OCI
        run: >
          devbox run -- just publish-chart-oci
          "${{ github.event.inputs.chart_repo }}"
          "${{ github.event.inputs.chart_name }}"
          "${{ github.event.inputs.chart_version }}"
